WebApplication1/Models/Song.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Xml.Serialization;

namespace WebApplication1.Models
{
    [Serializable, XmlRoot("song")]
    public class Song
    {
        [XmlAttribute(AttributeName = "song_id")]
        [Key]
        public int songID { get; set; }

        [XmlElement(ElementName = "title")]
        public String title { get; set; }

        [XmlElement(ElementName = "releaseYear")]
        public int year { get; set; }

        [XmlElement(ElementName = "genre")]
        public String genre { get; set; }

        [XmlElement(ElementName = "artist")]
        public virtual Artist artist { get; set; }

        [XmlElement(ElementName = "duration")]
        public int duration { get; set; }

        [XmlElement(ElementName = "lyrics")]
        public String lyrics { get; set; }

        [XmlElement(ElementName = "music")]
        public String music { get; set; }

        [XmlElement(ElementName = "album")]
        public virtual Album album { get; set; }

        [XmlElement(ElementName = "producer")]
        public virtual Producer producer { get; set; }

        [XmlElement(ElementName = "video")]
        public virtual Video video { get; set; }

    }
}

WebApplication1/Controllers/SongController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using System.Xml.Linq;
using System.Xml.Schema;
using System.Xml.Serialization;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class SongController : Controller
    {
        private ApplicationDbContext _context;

        public SongController()
        {
            _context = new ApplicationDbContext();

        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        public ViewResult Index()
        {
            var songs = _context.Songs.ToList();
            return View(songs);
        }

        public ActionResult Details(int id)
        {
            var song = _context.Songs.SingleOrDefault(c => c.songID == id);

            if (song == null)
                return HttpNotFound();

            return View(song);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Song newSong)
        {

            if (ModelState.IsValid)
            {
                _context.Songs.Add(newSong);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            else
            {
                return View(newSong);
            }
        }

        public static Song XmlToObject(Type type, string xml)
        {
            Song oOut = null;

            if (xml != null && xml.Length > 0)
            {
                System.Xml.Serialization.XmlSerializer serializer = new System.Xml.Serialization.XmlSerializer(type);

                using (System.IO.StringReader sReader = new System.IO.StringReader(xml))
                {
                    oOut = (Song)serializer.Deserialize(sReader);

                    sReader.Close();
                }
            }

            return oOut;
        }
        public static string ObjectToXML(Type type, object obby)
        {
            XmlSerializer ser = new XmlSerializer(type);
            using (System.IO.MemoryStream stm = new System.IO.MemoryStream())
            {
                ser.Serialize(stm, obby);
                stm.Position = 0;
                using (System.IO.StreamReader stmReader = new System.IO.StreamReader(stm))
                {
                    string xmlData = stmReader.ReadToEnd();
                    return xmlData;
                }
            }

        }

        public bool Validate(string inputUri)
        {
           /* XmlReaderSettings settings = new XmlReaderSettings();
            settings.DtdProcessing = DtdProcessing.Parse;
            settings.ValidationType = ValidationType.DTD;
            */
            XmlSchemaSet sc = new XmlSchemaSet();

            // Add the schema to the collection.
            sc.Add("urn:song-schema", "song_schema.xsd");

            XmlReaderSettings settings = new XmlReaderSettings();
            settings.ValidationType = ValidationType.Schema;
            settings.Schemas = sc;
            //settings.ValidationEventHandler += new ValidationEventHandler(ValidationCallBack);

            try
            {
                XmlReader reader = XmlReader.Create(inputUri, settings);
                while (reader.Read()) { }
                reader.Close();
            }
            catch (XmlSchemaException e)
            {
                Redirect("Error");
                return false;
            }
            catch (ArgumentException e)
            {
                return false;
            }
            catch (FileNotFoundException e)
            {
                return false;
            }
            catch (UriFormatException e)
            {
                return false;
            }
            catch (XmlException e)
            {
                return false;
            }

            return true;
        }
        
        //WRITE AND READ FROM XML
        //READ AND WRITE TO XML
        [Route("WriteXml")]
        public ContentResult WriteXml()
        {

            /*
                Get all database entries and convert them into xml files using the XDocument, X  
            */

            for (int i = 0; i < _context.Songs.ToList().Count; i++)
            {
                new XDocument(
                   new XElement("song",
                        new XAttribute("song_id", _context.Songs.ToList()[i].songID.ToString()),
                        new XElement("title", _context.Songs.ToList()[i].title),
                        new XElement("releaseYear", _context.Songs.ToList()[i].year.ToString()),
                        new XElement("genre", _context.Songs.ToList()[i].genre),
            // artist
                        new XElement("artist", 
                            new XAttribute("artist_id", _context.Songs.ToList()[i].artist.artistID.ToString()),
                            new XAttribute("age", _context.Songs.ToList()[i].artist.age.ToString()),
                            new XElement("artistStageName", _context.Songs.ToList()[i].artist.stage_name),
                            new XElement("artistName", _context.Songs.ToList()[i].artist.name),
                            new XElement("gender", _context.Songs.ToList()[i].artist.gender),
                            new XElement("birthdate", _context.Songs.ToList()[i].artist.birthdate),
                            new XElement("country", _context.Songs.ToList()[i].artist.country),
                            new XElement("image", _context.Songs.ToList()[i].artist.image)
                        ),
                        new XElement("duration", _context.Songs.ToList()[i].duration.ToString()),
            // album
                        new XElement("album",
                            new XAttribute("album_id", _context.Songs.ToList()[i].album.albumID.ToString()),
                            new XAttribute("releaseYear", _context.Songs.ToList()[i].album.year.ToString()),
                            new XAttribute("awards", _context.Songs.ToList()[i].album.awards),
                            new XElement("albumName", _context.Songs.ToList()[i].album.name),
                            new XElement("albumGenre", _context.Songs.ToList()[i].album.genre),
                            new XElement("numberOfTracks", _context.Songs.ToList()[i].album.tracks.ToString()),
                            new XElement("totalDuration", _context.Songs.ToList()[i].album.duration.ToString())
                        ),
            // producer
                        new XElement("producer",
                            new XAttribute("producer_id", _context.Songs.ToList()[i].producer.producerID.ToString()),
                            new XElement("producerCompany", _context.Songs.ToList()[i].producer.name),
                            new XElement("address", _context.Songs.ToList()[i].producer.address),
                            new XElement("phoneNumber", _context.Songs.ToList()[i].producer.phone)
                        ),
                        new XElement("lyrics", _context.Songs.ToList()[i].lyrics),
                        new XElement("music", _context.Songs.ToList()[i].music),
            // video
                        new XElement("video",
                            new XAttribute("video_id", _context.Songs.ToList()[i].video.videoID.ToString()),
                            new XElement("youTubeLink", _context.Songs.ToList()[i].video.link),
                            new XElement("publishedOn", _context.Songs.ToList()[i].video.date),
                            new XElement("numberOfViews", _context.Songs.ToList()[i].video.views.ToString()),
                            new XElement("numberOfLikes", _context.Songs.ToList()[i].video.likes.ToString()),
                            new XElement("numberOfDislikes", _context.Songs.ToList()[i].video.dislikes.ToString())
                        )
                     )

                )
                .Save("C:\\Users\\Kristin Stefanova\\source\\repos\\WebApplication1\\WebApplication1\\XML\\written\\" + i + ".xml");
            }

            return Content("Data from database writen to xml");
        }

        [Route("ReadXml")]
        public ContentResult ReadXml()
        {
            StringBuilder buildString = new StringBuilder();
            for (int i = 0; i < 21; i++)
            {
                XmlDocument doc = new XmlDocument();
                doc.XmlResolver = new XmlUrlResolver();
                doc.Load("C:\\Users\\Kristin Stefanova\\source\\repos\\WebApplication1\\WebApplication1\\XML\\readed\\song_" + i + ".xml");
                if (Validate("C:\\Users\\Kristin Stefanova\\source\\repos\\WebApplication1\\WebApplication1\\XML\\readed\\" + "song_" + i + ".xml"))
                {
                    Song description = XmlToObject(typeof(Song), doc.InnerXml);
                    buildString.Append(ObjectToXML(typeof(Song), description) + "\n");

                    _context.Songs.Add(description);
                    _context.SaveChanges();
                }

                else
                {
                    buildString.Append((i).ToString() + ", ");
                }
            }

            return Content(buildString.ToString());
        }

    }
}

WebApplication1/Views/Song/Create.cshtml
@model WebApplication1.Models.Song

@{
    ViewBag.Title = "Create";
}

<h2>Добавете ново музикално изпълнение</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true)

    <div class="form-group">
        <div class="col-md-10">
            Заглавие
            @Html.EditorFor(model => model.title)
            @Html.ValidationMessageFor(model => model.title)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.year, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.year)
            @Html.ValidationMessageFor(model => model.year)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.genre, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.genre)
            @Html.ValidationMessageFor(model => model.genre)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.title, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.title)
            @Html.ValidationMessageFor(model => model.title)
        </div>
    </div>






    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

WebApplication1/Views/Song/Details.cshtml
@model WebApplication1.Models.Song

@{
    ViewBag.Title = "Details";
}


<h2>Детайли</h2>
<div style="background-color:rgba(240, 240, 240, 0.6); height:240; width: 75%; border: 2px solid black; margin: auto; margin-bottom: 5px;">
    <iframe style="float:left; width:320px; height:240px;" src=@Model.video.link></iframe>
    <p style="margin-left: 340px;">
        @Model.title - @Model.artist.stage_name, @Model.year
    </p>
    <p style="margin-left: 340px;">
        Текст: @Model.lyrics
    </p>
    <p style="margin-left: 340px;">
        Музика: @Model.music
    </p>
    <p style="margin-left: 340px;">
        Информация за изпълнител: @Model.artist.name, @Model.artist.age год, @Model.artist.birthdate, @Model.artist.country
    </p>
    <p style="margin-left: 340px;">
        Албум: @Model.album.name - @Model.album.year
    </p>
    <p style="margin-left: 340px;">
        Продуцент: @Model.producer.name
    </p>
    <p style="margin-left: 340px;">
        Видео: Гледания @Model.video.views
    </p>
    <p style="margin-left: 340px;">
        Харесвания @Model.video.likes Нехаресвания @Model.video.dislikes
    </p>
</div>

WebApplication1/Views/Song/Index.cshtml
@model IList<WebApplication1.Models.Song>

@{
    ViewBag.Title = "Index";
}

<h2>Музикални изпълнения</h2>
@if (Model.Any())
{
    <table>
        <tr>
            <th>
                Заглавие                                    
            </th>
            <th>
                Изпълнител                                  
            </th>
            <th>
                Албум                                   
            </th>
            <th>

            </th>
        </tr>

        @foreach (var song in Model)
        {
            <tr>
                <td>
                    @song.title
                </td>
                <td>
                    @song.artist.stage_name
                </td>
                <td>
                    @song.album.name
                </td>
                <td>
                    @song.songID
                    @Html.ActionLink("Details", "Details", "Song", new { id = @song.songID }, null)
                </td>
            </tr>
        }
    </table>
}
else
{
    <h3>В момента няма музикални изпълнения</h3>
}

WebApplication1/Views/Song/Songs.cshtml
@model WebApplication1.Models.Song

@{
    ViewBag.Title = "Songs";
}

<h2>Songs</h2>